#! /bin/sh

chosen=$(printf "\n\n\n\n" | rofi -dmenu -i -theme-str '@import "power.rasi"')

case "$chosen" in
	"") poweroff ;;
	"") reboot ;;
	"") systemctl suspend ;;
	"") i3-msg exit ;;
	"") i3lock ;;
	*) exit 1 ;;
esac
