theme = "rose_pine"

[editor]
mouse = true
middle-click-paste = true
line-number = "absolute"
auto-format = false
color-modes = true
scrolloff = 5
cursorline = true

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.file-picker]
hidden = false
max-depth = 1

[editor.search]
smart-case = true
wrap-around = true

[editor.indent-guides]
render = true
character = "╎"
skip-levels = 1

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
X = ["extend_line_up", "extend_to_line_bounds"]
A-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
A-k = ["extend_to_line_bounds", "delete_selection", "move_visual_line_up", "paste_before"]

[keys.select]
X = ["extend_line_up", "extend_to_line_bounds"]
A-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
A-k = ["extend_to_line_bounds", "delete_selection", "move_visual_line_up", "paste_before"]

[keys.normal.z]
j = "page_down"
J = "half_page_down"
k = "page_up"
K = "half_page_up"

[keys.select.z]
j = "page_down"
J = "half_page_down"
k = "page_up"
K = "half_page_up"
