require('stav.plugin_config.gruvbox')
require('stav.plugin_config.lualine')
require('stav.plugin_config.nvim-tree')
require('stav.plugin_config.treesitter')
require('stav.plugin_config.telescope')
require('stav.plugin_config.lsp-config')
